version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - /Volumes/Storage/dumps/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped